### ISSUE TITLE
Effekt running 'clear' when running a main() via. "Run" button

### ISSUE THREAD

**Issue by TheDying0fLight** [TheDying0fLight/FairSweeper#18]
Effekt seems to always run `clear` before the function when using the `Run` button in Windows this does nothing except throwing an error bcs the command does not exist

![image](https://github.com/user-attachments/assets/df2e5b89-c58b-43ab-bfd5-2f47ff901665)

**Comment by jiribenes** [comment]
Yep, good catch, that's an [`effekt-vscode` issue](https://github.com/effekt-lang/effekt-vscode/issues), could you create/move the issue there, please?

**Comment by TheDying0fLight** [comment]
Moved to https://github.com/effekt-lang/effekt-vscode/issues/41
